### PR TITLE
Fix processing of common-suffix elements placed in root of MPT

### PR DESCRIPTION
**Pull request by boguslavsky**

### CODE REVIEW

**Comment by boguslavsky** [comment]
@slowli 
> Edit: forgot to add a condition that left[0..i] and right[0..i] should coincide.

this case in covered in the equations like:
```
keyPrefix.length === 0 && // root level
levelData.right === undefined &&
!isPrefixOf(levelData.left.suffix, branchValue.suffix) && // right key suffix is not a prefix of left key suffix
!isPrefixOf(branchValue.suffix, levelData.left.suffix) // left key suffix is not a prefix of right key suffix
```
so we throws error in this case.

**Comment by boguslavsky** [comment]
```
Correct me if I'm wrong, but it seems that the special case for the 2 edges stemming from the root of the tree, left and right, can be shortened to: there must exist an index i in 0..Math.min(left.length, right.length) such as left[i] === '0' and right[i] === '1'. If this is true, I'd prefer for the check to be implemented in this way; it's substantially easier to digest.
```
@slowli you almost right; but here is the reason to keep current realization:
- when tree is valid but branch keys has common prefix we need to identify which branch if left and which is right. This should be done because correct branch position is critical for calculation of root hash.

**Comment by slowli** [comment]
@boguslavsky I'm not saying that the current implementation is wrong; I'm just saying that organizing checks in a way I described could be more straightforward. Something like this:

```javascript
function orderKeys(x, y) {
  var len = Math.min(x.length, y.length);
  for (var i = 0; i < len; i++) {
    if (x[i] !== y[i]) {
      return x[i] === '0' ? [x, y] : [y, x];
    }
  }
  return null;
}

var orderedKeys = orderKeys(...);
if (orderedKeys) {
  var left = orderedKeys[0];
  var right = orderedKeys[1];
  // ...
} else {
  // Keys are unorderable
  throw new Error(...);
}
```

**Comment by boguslavsky** [comment]
@slowli i refactored code in the way you recommended. Please find updated code in #53

**Pull request closed without merging**
